# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.5
loader_version=0.16.14

# Mod Properties
mod_version=0.1.1
maven_group=de.olivermakesco
archives_base_name=polyspring

# Dependencies
fabric_api=0.124.2+1.21.5
geyser_api=2.7.0-SNAPSHOT
polymer_api=0.12.5+1.21.5
